Daily <- function() {
library(quantmod)
library(reshape2)
library(plyr)
library(dplyr)
library(readxl)
### load functions ###
source('~/Documents/Personal/DataScience/R/CumulativeReturnsV2.R')
source('~/Documents/Personal/DataScience/R/Opportunities2.R')
source('~/Documents/Personal/DataScience/R/DailyGraphV2.R')
source('~/Documents/Personal/DataScience/R/PLv2.R')
source('~/Documents/Personal/DataScience/R/LiveCumulative.R')
source('~/Documents/Personal/DataScience/R/MADirection.R')
source('~/Documents/Personal/DataScience/R/Opportunities2.R')
source('~/Documents/Personal/DataScience/R/Correlation.R')
source('~/Documents/Personal/DataScience/R/RelativeStrengthComparative.R')
### Setup daily data ###
        file.list <- list.files(path = "/Volumes/C/snet",pattern='*.csv')
        setwd("/Volumes/C/snet")
        df.lst <- lapply(file.list ,read.csv,skip = 5, header = FALSE, sep =",")        # read all csv's#
        bigdf <- ldply(df.lst, rbind)           # combine into one datafram
        bigdf <- bigdf[,1:11]
        bigdf <- bigdf[,-4]
        bigdf <- bigdf[,-4]
        names(bigdf) <- c("Name","Exchange","Instm", "Date","Open", "High", "Low", "Close", "Volume")
        JSEdat <- subset(bigdf[,-3],bigdf$Exchange %in% c("JSE","SPOT","FOREX"))
        JSEdat <- JSEdat[,-2]
        JSEdat$Date <- as.Date(as.character(JSEdat$Date),format="%Y%m%d")               #convert to char then date
        JSEdat$Volume <- as.numeric(JSEdat$Volume)        
### Live Trades ###        
Trades <- read_excel("/Users/johnlyons/Dropbox/CTS/Trades.xlsx",col_names = TRUE,na = "")
Trades <- as.data.frame(Trades)
Trades$Purchase <- as.Date(Trades$Purchase)
Trades$`Exit Dt` <- as.Date(Trades$`Exit Dt`)
mylst <- subset(Trades,is.na(Trades$Exit)) 
instLive <- as.character(mylst[,1])
### my Lists ###
CurrUSD <- c("C-USDAUD","C-USDCAD","C-USDCHF","C-USDGBP","C-USDEUR","C-USDJPY","C-USDZAR","C-USDEUR","C-USDCNY","C-BTCUSD")
CurrZAR <- c("C-EURZAR","C-GBPZAR","C-USDZAR","C-NZDZAR","C-ZARJPY")
Plat <- c("PLAT-$","RBPLAT","PLAT-R","JSE-PLAT","ANGLOPLAT","IMPLATS","LONMIN","NORTHAM")
Gold <- c("ANGGOLD"  ,"JSE-GOLD" ,"PAN-AF", "DRDGOLD" ,  "HARMONY" ,  "GFIELDS" ,  "SIBANYE",   "GOLD-R")
KeyIndixes <- c("BDI","JSE-CONS","JSE-PLAT","JSE-GOLD","JSE-INDI","JH-ALSI40","JSE-FINI","SP500","JSE-BANK","GOLD-R","JSE-RESI","JSE-INDM","C-YENZAR","USALB","NIKKEI","C-JPYUSD","BRENT")
MtlsIndexes <- c("JSE-CONS","JSE-PLAT","JSE-GOLD","JSE-INDI","JH-ALSI40","JSE-FINI","SP500","JSE-BANK","GOLD-R","JSE-INDM","C-YENZAR","USALB","NIKKEI","C-JPYUSD","BRENT","PLAT-$","PALLAD-$","NICKEL","ZINC-$","COPPER-$","SILV-$","BDI")

Metals <- c("COPPER-$","ZINC-$","NICKEL","BRENT","PALLAD-$","GOLD-R","PLAT-$","SILV-$","SILV-R")
Indm <- c("ARCMITTAL","SOUTH32","KUMBAIO")
JSE <- c("JSE-OILP","JSE-GOLD","JSE-COAL","JSE-PLAT","JSE-METL","JSE-INDM","JSE-ALSH","JSE-RESI","JSE-INDI","JSE-FINI","JSE-ALTX","JSE-AUTM","JSE-BEVR","JSE-FOOD","JSE-PHAR","JSE-OILG","JSE-HEAL","JSE-CONS","JSE-TELE","JSE-TECH","JSE-BANK","JSE-LIFE")
Banks <- c("STANBANK","NEDCOR","FIRSTRAND","CAPITEC","DISCOVERY","JSE-BANK")
Food <- c("RCL","CLOVER","RHODES","A-V-I","OCEANA","ASTRAL","TONGAAT","PNR-FOODS","TIGBRANDS","JSE-FOOD")
Metl <- c("GLENCORE","ARM","ANGLO","BILLITON","ASSORE")
Cons <- c("ADVTECH","BIDCORP","CHOPPIES","CITYLDG","CLICKS","CURRO","CASHBIL","FAMBRANDS","HOLDSPORT","ITLTILE",
          "MRPRICE","MASSMART","NASPERSN","PICKNPAY","SHOPRIT","SPAR","SUNINT","TFG","TRUWTHS","WOOLIES")
IntInd <- c("NASDAQ",            "MSCI-EMM",            "SP500",            "DAX-INDEX",            "ALL-ORDS",            "TSE300",            "CAC-40",            "HANG-SENG",            "SET-INDEX",            "FT-100",            "NIKKEI",            "SENSEX",            "SHANGHAIC",            "SMI",            "MEX-IPC",            "BRAZ-BOV")
Resi <- c("ANGLO","ANGLOPLAT","ANGGOLD","BILLITON","GFIELDS","IMPLATS","SAPPI","SIBANYE","SASOL")
VolZar <- c("SAVI","C-USDZAR")
jl <- c("COPPER-$","GOLD-R")
jl1 <- c("ZINC-$","JSE-INDM")
jl2 <- c("GOLD-R","JSE-GOLD")
jl3 <- c("C-USDJPY","GOLD-PM")
YenZar <- c("C-YENZAR","GOLD-R")
CorrHealthPhar <- c("JSE-HEAL","JSE-PHAR")
Corr1 <- c("JSE-INDI","JSE-CONS","JH-ALSI40","JSE-FINI")
CorrYenZar <- c("NIKKEI","C-YENZAR","JSE-FINI","JSE-BANK")
Corr3 <- c("C-YENZAR","GOLD-R")
Corr4 <- c("JSE-GOLD","JSE-PLAT")
Corr5 <- c("ZINC-$","SILV-$")
CorrGoldR <- c("GOLD-R","JSE-GOLD","JSE-CONS")
CorrNegNikkei <- c("NIKKEI","JSE-GOLD","JSE-PLAT")
CorrUsalb <- c("USALB","NIKKEI","JSE-GOLD")
### ----------------###
### Generate Graphs ###
### ----------------###
CumulativeReturns("2016-11-14",Food,"Food")
CumulativeReturns("2017-01-01",Metl,"Metl")
CumulativeReturns("2016-10-01",Indm,"Indm")
CumulativeReturns("2016-11-05",KeyIndixes,"KeyIndixes")
CumulativeReturns(Sys.Date()-10,JSE,"JSE")
CumulativeReturns(Sys.Date()-20,IntInd,"IntInd")
CumulativeReturns("2016-06-01","NIKKEI","Nikkei")
CumulativeReturns("2016-06-01","BDI","Baltic")
CumulativeReturns("2016-06-01","USALB","TNote10")
CumulativeReturns("2016-08-25",Banks,"Banks")
CumulativeReturns(Sys.Date()-30,instLive,"Live")
CumulativeReturns("2016-12-20",Plat,"Plat")
CumulativeReturns("2016-12-15",Gold,"Gold")
CumulativeReturns(Sys.Date()-10,Metals,"Metals")
CumulativeReturns(Sys.Date()-20,CurrUSD,"CurrUSD")
CumulativeReturns("2016-07-01",CurrZAR,"CurrZAR")
CumulativeReturns("2016-07-01","USD-INDEX","USD")
CumulativeReturns(Sys.Date() - 10,Watchlist,"Watchlist")
#CumulativeReturns("2016-09-01",WatchFilt,"WatchFilt")
CumulativeReturns("2017-01-01",jl,"JL")
CumulativeReturns("2016-11-01",jl1,"JL1")
CumulativeReturns("2017-01-01",jl2,"GoldMetals")
CumulativeReturns("2016-07-01",jl3,"JL3")
CumulativeReturns("2016-07-01",YenZar,"ZarJpy")
CumulativeReturns("2017-01-01",CorrHealthPhar,"HealthPhar")
CumulativeReturns("2017-01-01",Corr1,"MainInd")
CumulativeReturns("2017-01-01",CorrYenZar,"CorrYenZar")
CumulativeReturns("2016-11-01",Corr3,"Corr3")
CumulativeReturns("2017-01-01",Corr4,"Corr4")
CumulativeReturns("2016-11-01",CorrNegNikkei,"CorrNikkei")
CumulativeReturns("2016-11-01",CorrUsalb,"Corr10YT")
CumulativeReturns("2015-11-01",VolZar,"VolZar")
DailyGraph(KeyIndixes)
DailyGraph(instLive)
DailyGraph(Watchlist)
DailyGraph(Banks)
DailyGraph(Gold)
DailyGraph(Plat)
DailyGraph(WatchFilt)
DailyGraph(Metl)
DailyGraph(Metals)
DailyGraph(IntInd)
DailyGraph(jl1)
DailyGraph(CurrZAR,"2016-07-01")
ProffitLoss()
LiveCumulative()
RSC()
Correlation()
MADirection()
#WrWeek()
Opportunities()
currLst <- c("BTC/ZAR","JPY/ZAR","USD/JPY","NZD/ZAR")
tickers <- c("^N225","^GSPC")
getSymbols(tickers)
getFX(currLst)
chartSeries(BTCZAR,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(NZDZAR,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(JPYZAR,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(USDJPY,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(N225,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-11-15::")
chartSeries(GSPC,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-11::")
}
