Daily <- function() {
library(quantmod)
library(reshape2)
library(plyr)
library(dplyr)
library(tidyr)
library(readxl)
### load functions ###
source('~/Documents/Personal/DataScience/R/JL CTS scripts/CumulativeReturnsV2.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/Opportunities2.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/DailyGraphV3.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/WeeklyGraph.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/PLv2.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/LiveCumulative.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/MADirection.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/Opportunities2.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/Correlation.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/RelativeStrengthComparative.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/RscHeatmapOrdered.R')        
### Setup daily data ###
        file.list <- list.files(path = "/Users/johnlyons/Desktop/snet",pattern='*.csv')
        setwd("/Users/johnlyons/Desktop/snet")
        df.lst <- lapply(file.list ,read.csv,skip = 5, header = FALSE, sep =",")        # read all csv's#
        bigdf <- ldply(df.lst, rbind)           # combine into one datafram
        bigdf <- bigdf[,1:11]
        bigdf <- bigdf[,-4]
        bigdf <- bigdf[,-4]
        names(bigdf) <- c("Name","Exchange","Instm", "Date","Open", "High", "Low", "Close", "Volume")
        JSEdat <- subset(bigdf[,-3],bigdf$Exchange %in% c("JSE","SPOT","FOREX"))
        JSEdat <- JSEdat[,-2]
        JSEdat$Date <- as.Date(as.character(JSEdat$Date),format="%Y%m%d")               #convert to char then date
        JSEdat$Volume <- as.numeric(JSEdat$Volume)  
        JSEdat <- JSEdat[JSEdat$Date != "2019-07-18",]          # remove dirty data
        write.csv(JSEdat,file = "/Users/johnlyons/Documents/Personal/DataScience/R/JSEdat.csv")
### Live Trades ###        
Trades <- read_excel("/Users/johnlyons/Dropbox/CTS/Trades.xlsx",col_names = TRUE,na = "")
Trades <- as.data.frame(Trades)
Trades$Purchase <- as.Date(Trades$Purchase)
Trades$`Exit Dt` <- as.Date(Trades$`Exit Dt`)
mylst <- subset(Trades,is.na(Trades$Exit)) 
RSC()

## Search for instr     ##
        ##      unique(JSEdat[grepl("SIB",JSEdat$Name),1])
        ##      
        ##      View(unique(sort(bigdf[,2])))   ##View of all inst
        ##      View((((bigdf[bigdf$Date == "20200401",]))))

        ### my Lists ###
CurrUSD <- c("C-USDAUD","C-USDCAD","C-USDCHF","C-USDGBP","C-USDEUR","C-USDJPY","C-USDZAR","C-USDEUR","C-USDCNY","C-BTCUSD")
CurrZAR <- c("C-EURZAR","C-GBPZAR","C-USDZAR","C-NZDZAR","C-ZARJPY")
Plat <- c("PLAT-$","RBPLAT","PLAT-R","JSE-PLAT","ANGLOPLAT","IMPLATS","NORTHAM")
Gold <- c("ANGGOLD"  ,"JSE-GOLD" ,"PAN-AF", "DRDGOLD" ,  "HARMONY" ,  "GFIELDS" ,  "SIBANYE-S",   "GOLD-R","GOLD-PM")
KeyIndixes <- c("BDI","JSE-CONS","JSE-PLAT","JSE-GOLD","JSE-INDI","JH-ALSI40","JSE-FINI","SP500","JSE-BANK","GOLD-R","JSE-RESI","JSE-INDM","C-YENZAR","USALB","NIKKEI","C-JPYUSD","BRENT")
MtlsIndexes <- c("JSE-PHAR","JSE-CONS","JSE-PLAT","JSE-GOLD","JSE-INDI","JH-ALSI40","JSE-FINI","SP500","JSE-BANK","GOLD-R","JSE-INDM","C-YENZAR","USALB","NIKKEI","C-JPYUSD","BRENT","PLAT-$","PALLAD-$","NICKEL","ZINC-$","COPPER-$","SILV-$","BDI")
indi <- c("NETCARE","LIFEHC","STEINHOFF","PICKNPAY","WOOLIES","TRUWTHS","RICHEMONT","MTN","MEDCLIN","CLICKS","VODACOM","BIDVEST","TFG","MRPRICE","IMPERIAL","SPAR","SHOPRIT","REMGRO","BIDCORP","ASPEN","TIGBRANDS","BATS","NASPERSN")
Metals <- c("COPPER-$","ZINC-$","NICKEL","BRENT","PALLAD-$","GOLD-R","PLAT-$","SILV-$","SILV-R")
Indm <- c("ARCMITTAL","SOUTH32","KUMBAIO")
JSE <- c("JSE-OILP","JSE-GOLD","JSE-COAL","JSE-PLAT","JSE-METL","JSE-INDM","JSE-ALSH","JSE-RESI","JSE-INDI","JSE-FINI","JSE-ALTX","JSE-AUTM","JSE-BEVR","JSE-FOOD","JSE-PHAR","JSE-OILG","JSE-HEAL","JSE-CONS","JSE-TELE","JSE-TECH","JSE-BANK","JSE-LIFE")
Banks <- c("ABSAG","STANBANK","NEDCOR","FIRSTRAND","CAPITEC","DISCOVERY","JSE-BANK")
Food <- c("RCL","CLOVER","RHODES","A-V-I","OCEANA","ASTRAL","TONGAAT","PNR-FOODS","TIGBRANDS","JSE-FOOD")
Metl <- c("GLENCORE","ARM","ANGLO","BILLITON","ASSORE")
Cons <- c("ADVTECH","BIDCORP","CHOPPIES","CITYLDG","CLICKS","CURRO","CASHBIL","FAMBRANDS","HOLDSPORT","ITLTILE",
          "MRPRICE","MASSMART","NASPERSN","PICKNPAY","SHOPRIT","SPAR","SUNINT","TFG","TRUWTHS","WOOLIES")
IntInd <- c("NASDAQ",            "MSCI-EMM",            "SP500",            "DAX-INDEX",            "ALL-ORDS",            "TSE300",            "CAC-40",            "HANG-SENG",            "SET-INDEX",            "FT-100",            "NIKKEI",            "SENSEX",            "SHANGHAIC",            "SMI",            "MEX-IPC",            "BRAZ-BOV")
Tech <- c("EOH","DATATEC","ALTRON")
JlRes <- c("GLENCORE","ARM","ANGLO","BILLITON","ASSORE","EXXARO","KUMBAIO")
Resi <- c("ANGLO","ANGLOPLAT","ANGGOLD","BILLITON","GFIELDS","IMPLATS","SAPPI","SIBANYE-S","SASOL")
Health <- c("ASPEN","ADCOCK","ASCENDIS","MEDCLIN","NETCARE")
Tele <- c("BLUETEL","TELKOM","MTN","VODACOM")
Phar <- c("ASCENDIS","ASPEN","ADCOCK")
VolZar <- c("SAVI","C-USDZAR")
jl <- c("COPPER-$","GOLD-R")
jl1 <- c("ZINC-$","JSE-INDM")
jl2 <- c("GOLD-R","JSE-GOLD")
jl3 <- c("C-USDJPY","GOLD-PM")
YenZar <- c("C-ZARJPY","GOLD-R")
CorrHealthPhar <- c("JSE-HEAL","JSE-PHAR","JSE-BANK")
Corr1 <- c("JSE-INDI","JSE-CONS","JH-ALSI40","JSE-FINI")
CorrYenZar <- c("NIKKEI","C-YENZAR","JSE-FINI","JSE-BANK")
Corr3 <- c("GOLD-R","JSE-BANK")
Corr4 <- c("JSE-GOLD","JSE-PLAT")
Corr5 <- c("ZINC-$","SILV-$")
Corr6 <- c("JSE-PLAT","PLAT-$")
Corr7 <- c("JSE-GOLD","USALB")
CorrGoldR <- c("GOLD-R","JSE-GOLD","JSE-CONS")
CorrNegNikkei <- c("NIKKEI","JSE-GOLD","JSE-PLAT")
CorrNikkei <- c("NIKKEI","USALB")
CorrUsalb <- c("USALB","NIKKEI")
currLst <- c("BTC/ZAR","JPY/ZAR","USD/JPY","NZD/ZAR")
tickers <- c("^N225","^GSPC")
### ----------------###
### Generate Graphs ###
### ----------------###
CumulativeReturns(Sys.Date()-7,to_graph,"TopPerformers7")
CumulativeReturns(Sys.Date()-30,to_graph,"TopPerformers30")
CumulativeReturns(Sys.Date()-60,to_graph,"TopPerformers60")
CumulativeReturns(Sys.Date() - 20,Food,"Food")
CumulativeReturns("2018-11-04",Phar,"Phar")
CumulativeReturns("2019-01-04",Metl,"Metl")
CumulativeReturns(Sys.Date() - 20,JlRes,"JLRes")
CumulativeReturns("2019-01-10",Indm,"Indm1")
CumulativeReturns(Sys.Date() - 20,KeyIndixes,"KeyIndixes")
CumulativeReturns(Sys.Date()-10,JSE,"JSE")
CumulativeReturns(Sys.Date()-60,mylst[,1],"Live60")
CumulativeReturns(Sys.Date()-7,mylst[,1],"Live7")
CumulativeReturns(Sys.Date()-20,IntInd,"IntInd")
CumulativeReturns("2019-01-04","NIKKEI","Nikkei")
CumulativeReturns("2019-01-04","BDI","Baltic")
CumulativeReturns("2019-01-04","USALB","TNote10")
CumulativeReturns("2019-01-04",Banks,"Banks")
CumulativeReturns(Sys.Date()-60,Cons,"Cons60")
CumulativeReturns(Sys.Date()-30,Cons,"Cons30")
CumulativeReturns(Sys.Date()-120,Tele,"Telecoms120")
CumulativeReturns("2018-08-04",Plat,"Plat LT")
CumulativeReturns(Sys.Date() - 30,Plat,"Plat")
CumulativeReturns("2018-08-05",Gold,"Gold")
CumulativeReturns(Sys.Date() - 30,Gold,"Gold1")
CumulativeReturns(Sys.Date()-10,Metals,"Metals10")
CumulativeReturns(Sys.Date()-40,Tech,"Tech40")
CumulativeReturns(Sys.Date()-20,CurrUSD,"CurrUSD20")
CumulativeReturns("2019-01-04",CurrZAR,"CurrZAR")
CumulativeReturns("2019-01-04","USD-INDEX","USD")
CumulativeReturns(Sys.Date() - 10,Watchlist,"Watchlist")
CumulativeReturns("2019-01-04",jl,"JL")
CumulativeReturns("2019-01-04",jl1,"JL1")
CumulativeReturns("2018-12-02",jl2,"GoldMetals")
CumulativeReturns("2019-11-04",jl3,"UsdJpy-Au")
CumulativeReturns("2019-08-04",YenZar,"YenZar")
CumulativeReturns("2018-08-04",CorrHealthPhar,"HealthPhar")
CumulativeReturns("2019-02-01",Health,"Health")
CumulativeReturns("2019-11-20",Corr1,"MainInd")
#CumulativeReturns("2017-01-01",CorrYenZar,"CorrYenZar")
CumulativeReturns("2019-08-04",Corr3,"Corr3-Note Inverse relation Gold to Banks")
CumulativeReturns("2019-03-15",Corr4,"JSE AU - Plat")
CumulativeReturns("2019-08-04",Corr6,"Plat : Plat-$")
CumulativeReturns("2019-08-04",VolZar,"VolZar")
DailyGraph(KeyIndixes,"2018-04-01")
DailyGraph(instLive)
DailyGraph(Watchlist,"2018-04-01")
DailyGraph(JlRes,"2018-04-01")
DailyGraph(Banks,"2018-09-01")
DailyGraph(Tech,"2018-02-01")
DailyGraph(Gold,"2018-07-01")
DailyGraph(Plat,"2018-07-01")
DailyGraph(WatchFilt)
DailyGraph(Metl,"2017-04-01")
DailyGraph(Indm,"2018-04-01")
DailyGraph(Metals)
DailyGraph(IntInd)
DailyGraph(Health)
DailyGraph(Phar,"2017-03-01")
DailyGraph(jl1)
DailyGraph(CurrZAR,"2016-07-01")
DailyGraph(Greenlst,"2016-04-01")
DailyGraph(Redlst,"2016-04-01")
ProffitLoss()
LiveCumulative()


Correlation()
MADirection()
#WrWeek()
Opportunities()
getSymbols(tickers)
getFX(currLst)
chartSeries(BTCZAR,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(NZDZAR,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(JPYZAR,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(USDJPY,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-04::")
chartSeries(N225,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-11-15::")
chartSeries(GSPC,multi.col = TRUE, theme = "black", TA="addMACD();addBBands()",subset = "2016-11::")
}
