fnInstrm <- function() {
        
        CurrUSD <<- c("C-USDAUD","C-USDCAD","C-USDCHF","C-USDGBP","C-USDEUR","C-USDJPY","C-USDZAR","C-USDEUR","C-USDCNY","C-BTCUSD")
        CurrZAR <<- c("C-EURZAR","C-GBPZAR","C-USDZAR","C-NZDZAR","C-ZARJPY")
        PLAT <<- c("RBPLAT","ANGLOPLAT","IMPLATS","NORTHAM","SIBANYE-S")
        GOLD <<- c("ANGGOLD"   ,"PAN-AF", "DRDGOLD" ,  "HARMONY" ,  "GFIELDS")
        KeyIndixes <<- c("BDI","JSE-CONS","JSE-PLAT","JSE-GOLD","JSE-INDI","JH-ALSI40","JSE-FINI","SP500","JSE-BANK","GOLD-R","JSE-RESI","JSE-INDM","C-YENZAR","USALB","NIKKEI","C-JPYUSD","BRENT")
        MtlsIndexes <<- c("JSE-PHAR","JSE-CONS","JSE-PLAT","JSE-GOLD","JSE-INDI","JH-ALSI40","JSE-FINI","SP500","JSE-BANK","GOLD-R","JSE-INDM","C-YENZAR","USALB","NIKKEI","C-JPYUSD","BRENT","PLAT-$","PALLAD-$","NICKEL","ZINC-$","COPPER-$","SILV-$","BDI")
        indi <<- c("AVI","PROSUS","NETCARE","LIFEHC","STEINHOFF","PICKNPAY","WOOLIES","TRUWTHS","RICHEMONT","MTN","MEDCLIN","CLICKS","VODACOM","BIDVEST","TFG","MRPRICE","IMPERIAL","SPAR","SHOPRIT","REMGRO","BIDCORP","ASPEN","TIGBRANDS","BATS","NASPERSN")
        Metals <<- c("COPPER-$","ZINC-$","NICKEL","BRENT","PALLAD-$","GOLD-R","PLAT-$","SILV-$","SILV-R")
        Indm <<- c("KUMBAIO")
        JSE <<- c("JSE-OILP","JSE-GOLD","JSE-COAL","JSE-PLAT","JSE-METL","JSE-INDM","JSE-ALSH","JSE-RESI","JSE-INDI","JSE-FINI","JSE-ALTX","JSE-AUTM","JSE-BEVR","JSE-FOOD","JSE-PHAR","JSE-OILG","JSE-HEAL","JSE-CONS","JSE-TELE","JSE-TECH","JSE-BANK","JSE-LIFE")
        BANK <<- c("ABSAG","STANBANK","NEDCOR","FIRSTRAND","CAPITEC","DISCOVERY","JSE-BANK")
        FOOD <<- c("RCL","CLOVER","RHODES","A-V-I","OCEANA","ASTRAL","TONGAAT","PNR-FOODS","TIGBRANDS","JSE-FOOD")
        METL <<- c("GLENCORE","ARM","ANGLO","BILLITON","ASSORE")
        CONS <<- c("ADVTECH","BIDCORP","CHOPPIES","CITYLDG","CLICKS","CURRO","CASHBIL","FAMBRANDS","HOLDSPORT","ITLTILE",
                  "MRPRICE","MASSMART","NASPERSN","PICKNPAY","SHOPRIT","SPAR","SUNINT","TFG","TRUWTHS","WOOLIES")
        IntInd <<- c("NASDAQ",            "MSCI-EMM",            "SP500",            "DAX-INDEX",            "ALL-ORDS",            "TSE300",            "CAC-40",            "HANG-SENG",            "SET-INDEX",            "FT-100",            "NIKKEI",            "SENSEX",            "SHANGHAIC",            "SMI",            "MEX-IPC",            "BRAZ-BOV")
        TECH <<- c("PROSUS","DATATEC","ALTRON", "NASPERSN")
        JlRes <<- c("GLENCORE","ARM","ANGLO","BILLITON","ASSORE","EXXARO","KUMBAIO")
        RESI <<- c("ANGLO","ANGLOPLAT","ANGGOLD","BILLITON","GFIELDS","IMPLATS","SAPPI","SIBANYE-S","SASOL")
        HEAL <<- c("ASPEN","ADCOCK","ASCENDIS","MEDCLIN","NETCARE")
        TELE <<- c("BLUETEL","TELKOM","MTN","VODACOM")
        PHAR <<- c("ASCENDIS","ASPEN","ADCOCK")
        VolZar <<- c("SAVI","C-USDZAR")
        jl <<- c("COPPER-$","GOLD-R")
        jl1 <<- c("ZINC-$","JSE-INDM")
        jl2 <<- c("GOLD-R","JSE-GOLD")
        jl3 <<- c("C-USDJPY","GOLD-PM")
        YenZar <<- c("C-ZARJPY","GOLD-R")
        CorrHealthPhar <<- c("JSE-HEAL","JSE-PHAR","JSE-BANK")
        Corr1 <<- c("JSE-INDI","JSE-CONS","JH-ALSI40","JSE-FINI")
        CorrYenZar <<- c("NIKKEI","C-YENZAR","JSE-FINI","JSE-BANK")
        Corr3 <<- c("GOLD-R","JSE-BANK")
        Corr4 <<- c("JSE-GOLD","JSE-PLAT")
        Corr5 <<- c("ZINC-$","SILV-$")
        Corr6 <<- c("JSE-PLAT","PLAT-$")
        Corr7 <<- c("JSE-GOLD","USALB")
        CorrGoldR <<- c("GOLD-R","JSE-GOLD","JSE-CONS")
        CorrNegNikkei <<- c("NIKKEI","JSE-GOLD","JSE-PLAT")
        CorrNikkei <<- c("NIKKEI","USALB")
        CorrUsalb <<- c("USALB","NIKKEI")
        currLst <<- c("BTC/ZAR","JPY/ZAR","USD/JPY","NZD/ZAR")
        tickers <<- c("^N225","^GSPC")
}

