---
output: html_document
fig_width: 23
fig.align: "center"

---
        
<style type="text/css">
        .main-container {
                max-width: 1800px;
                margin-left: auto;
                margin-right: auto;
        }
</style>
        
```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(TTR)
library(quantmod)
library(reshape2)
library(plyr)
library(dplyr)
library(tidyr)
library(readxl)
library(reshape2)
library(DT)
library(plotly)
library(dygraphs)

source('~/Documents/Personal/DataScience/R/JL CTS scripts/DailyGraphNoPng.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/WeeklyGraph.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/RscHeatmap.R')
source('~/Documents/Personal/DataScience/R/JL CTS scripts/RelativeStrengthComparative.R')
source("/Users/johnlyons/Documents/Personal/DataScience/R/JL CTS scripts/PLv2.R")
source("/Users/johnlyons/Documents/Personal/DataScience/R/JL CTS scripts/CumRet.R")
source("/Users/johnlyons/Documents/Personal/DataScience/R/JL CTS scripts/CumRetDyG.R")
source("/Users/johnlyons/Documents/Personal/DataScience/R/JL CTS scripts/RelativeStrengthComparativeAllSegments.R")




excl_list <- ("AGLSBB|AMSSBE|AMSSBP|ANGSBA|ANGSBO|ANGSBY|APNSBG|APNSBH|ASHINF|ASHMID|ASHT40|ASHWGB|BLUSBH|BHPSBF|CSP500|CSPROP|CTOP50|DIPULA-A|DIPULA-B|EQUITES|ETF5IT|ETFGLD|ETFPLD|ETFPLT|ETFSAP|FIRSTRNDP|GFISBC|GFISBD|GFISBT|HARSBW|HARSBO|IMPSBH|IMPSBI|IMPSBV|INDLU|J200USD|JH-ALEX|JH-ALSI40|JH-ASIN|JH-FLED|JH-MIDCAP|JH-RES|JH-SMALL|JSE|JSE-ALPI|JSE-ALSH|JSE-ALT15|JSE-ALTX|JSE-AUTM|JSE-BANK|JSE-BASM|JSE-BEVR|JSE-CALS|JSE-CHES|JSE-CIN25|JSE-COAL|JSE-CONG|JSE-CONM|JSE-CONS|JSE-CPI|JSE-CTOP|JSE-DALS|JSE-DIVP|JSE-DTOP|JSE-ELEE|JSE-EQII|JSE-FINA|JSE-FINDI|JSE-FINI|JSE-FJGI|JSE-FJVI|JSE-FOOD|JSE-FOOR|JSE-FORE|JSE-FTEL|JSE-GENF|JSE-GENI|JSE-GERE|JSE-GOLD|JSE-HCOM|JSE-HEAL|JSE-HEES|JSE-HOUS|JSE-IIND|JSE-INDE|JSE-INDI|JSE-INDM|JSE-INDT|JSE-LGCAP|JSE-LIFE|JSE-MEDI|JSE-METL|JSE-MINI|JSE-MTEL|JSE-NLIF|JSE-OILG|JSE-OILP|JSE-PERG|JSE-PHAR|JSE-PLAT|JSE-PRUT|JSE-PULS|JSE-REDS|JSE-REIV|JSE-RESI|JSE-SAPI|JSE-SCOM|JSE-SCTP|JSE-SRI|JSE-SUPS|JSE-SW40|JSE-SWALS|JSE-SXTRI|JSE-TABA|JSE-TECH|JSE-TELE|KIOSBN|MRPSBG|NPNSBA|MTNSBB|GFISBU|SBKSBB|NPNSBB|NPNSBC|NPNSBP|NPNSBZ|Nedbank-P|PRXSBQ|PSG-KST|SATRIX40|SATRIX500|SATRIXDIV|SATRIXEMG|SATRIXNDQ|SATRIXRAF|SATRIXRES|SATRIXSWX|SATRIXWRD|SBEN05|SBKSBO|SGLSBC|SGLSBD|SGLSBE|SGLSBU|SGLSTD|SHPSBG|SOLSBC|SOLSBE|STANBANKP|STXFIN|STXILB|STXIND|STXPRO|STXQUA|SYG4IRGE|SYGEURO50|SYGSP500|SYGSWIX40|TOPSBA|TOPSBB|TOPSBN|TOPSBO|TOPSBW|TOPSBX|TOPSBY|UBNPNE|VODSBG|ZA077|ZA079|WHLSBD|WHLSBE|ZAMBEZI-P")


Indexes <- unique(c("JSE-GOLD","JSE-ALSH","JSE-LGCAP","JSE-RESI","JSE-INDI","JSE-FINI","JSE-TECH","JSE-TELE","JSE-HEAL","JSE-REALE","JSE-CONSD","JSE-CONST","JSE-ENRGY","JSE-BANK","JSE-LIFE","JSE-CONSS","JSE-RETAL","JSE-BEVR","JSE-FOOD","JSE-TABAC","JSE-PDG","JSE-CONM","JSE-INDM","JSE-CHES","JH-ALSI40","SP500","NASDAQ","NIKKEI","C-USDZAR","C-BTCUSD","GOLD-R","SILV-R","C-BTCUSD","C-ETHUSD"))

IND <- c("JSE-FINI","BTCZAR","GOLD-R","SILV-R","JSE-INDI","C-USDZAR","JSE-TECH","JSE-GOLD","NIKKEI","JSE-PLAT","JSE-METL","UALSB","JSE-INDM","JSE-FOOD","JSE-PHAR","JSE-OILG","JSE-HEAL","SP500","JH-ALSI40","JSE-COAL","JSE-RESI","JSE-ALTX","JSE-BANK","BRENT","JSE-AUTM","JSE-CHES")

PDG <- c("BIDCORP","CLICKS","DIS-CHEM","PICKNPAY","SHOPRIT","SPAR")
CONM <- c("PPC","RAUBEX","WBHO")
LIFE <- c("DISCOVERY","MOMENTUM","SANLAM","OMUTUAL")
CONSS <- c("ADVTECH","CURRO")
CHES <- c("AECI","OMNIA","SASOL")
PLAT <- c("RBPLAT","ANGLOPLAT","IMPLATS","NORTHAM","SIBANYE-S")
GOLD <- c("ANGGOLD"   ,"PAN-AF", "DRDGOLD" ,  "HARMONY" ,  "GFIELDS")
INDM <- c("KUMBAIO")
BANK <- c("ABSAG","STANBANK","NEDCOR","FIRSTRAND","CAPITEC","DISCOVERY")
FOOD <- c("RCL","CLOVER","RHODES","A-V-I","OCEANA","ASTRAL","TONGAAT","PNR-FOODS","TIGBRANDS","JSE-FOOD")
METL <- c("GLENCORE","ARM","ANGLO","BHPGROUP")
CONS <- c("ADVTECH","BIDCORP","CITYLDG","CLICKS","CURRO","CASHBIL","FAMBRANDS","ITLTILE",
          "MRPRICE","MASSMART","NASPERSN","PICKNPAY","SHOPRIT","SPAR","SUNINT","TFG","TRUWTHS","WOOLIES")
TECH <- c("PROSUS","DATATEC","ALTRON", "NASPERSN")
RESI <- c("ANGLO","ANGLOPLAT","ANGGOLD","GFIELDS","IMPLATS","SAPPI","SIBANYE-S","SASOL","BHPGROUP")
HEAL <- c("ASPEN","ADCOCK","LIFEHC","NETCARE")
TELE <- c("BLUETEL","TELKOM","MTN","VODACOM")
PHAR <- c("ASCENDIS","ASPEN","ADCOCK")
OILG <- c("MNTKRENEW","SASOL")
ENRGY <- c("MNTKRENEW","EXXARO","TGALTD")
BEVR <- c("ABINBEV")
COAL <- "EXXARO"
NEWGOLD <- "NEWGOLD"
INDI <- c("ABINBEV","ASPEN","AVLN","BIDVEST","RICHEMONT","CLICKS","LIFEHC","MTN","NASPERSN",
          "NETCARE","PICKNPAY","PROSUS","SHOPRIT","SPAR","TIGBRANDS","TFG","TRUWTHS","VODACOM","WOOLIES",
          "MCGROUP","MRPRICE","BATS","BARWORLD","BIDCORP")
FINI <- c("CAPITEC","DISCOVERY","FIRSTRAND","GROWPNT","INVLTD","INVPLC","NEDCOR","NEPIROCK",
          "OMUTUAL","REDEFINE","REMGRO","RMBH","REINET","SANLAM","STANBANK","ABSAG")

CURR <- c("C-AUDUSD","C-AUDZAR","C-CADEUR","C-CADGBP","C-CADUSD","C-CADZAR","C-CHFUSD","C-EURCAD","C-EURGBP","C-EURJPY","C-EURUSD","C-EURZAR","C-GBPCAD","C-GBPUSD","C-GBPZAR","C-JPYAUD","C-JPYEUR","C-JPYUSD","C-NZDUSD","C-NZDZAR","C-USDAUD","C-USDCAD","C-USDEUR","C-USDGBP","C-USDJPY","C-USDNZD","C-USDRUB","C-USDZAR","C-ZARUSD","C-USDINR","C-USDCNY","C-ZARNZD","C-ZARAUD","C-ZAREUR","C-YENZAR","C-ZARGBP","C-ZARCAD","C-SWFZAR","GOLD-R","SILV-R","C-BTCUSD","C-ETHUSD")

Commods<- c("COBALTM","NICKEL","ZINC-$","OIL-LIGHT","GOLD-NY","WTI_CRUDE","RHODIUM","IRIDIUM","SILV-$","GOLD-PM","PALLAD-$","BRENT","COPPER-$","URANIUM")

RETAIL <- c("CASHBUILD","ITALTILE","MRPRICE","MOTUS","PEPKOR","TFG","TRUWTHS","WOOLIES")



```


